VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Arkusz1"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = True
Attribute VB_Exposed = True

Private Sub CommandButton1_Click()

    wskaz_plik_konfiguracyjny

End Sub

Private Sub CommandButton2_Click()

    otworz_plik_konfiguracyjny

End Sub

Private Sub CommandButton3_Click()

    stworzAK2

End Sub

Private Sub CommandButton4_Click()

    stworzDat

End Sub

Private Sub CommandButton5_Click()

    dodajPrzedrostkiDoSystemow

End Sub
